/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.oop.academy.presentation.course;

import com.oop.academy.models.Category;
import com.oop.academy.models.Course;
import com.oop.academy.models.Teacher;
import com.oop.academy.presentation.MainFrame;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author MSI
 */
public class CoursesView extends javax.swing.JPanel {

    List<Course> courses = new ArrayList();

    /**
     * Creates new form CoursesView
     *
     * @param mainFrame
     */
    public CoursesView(MainFrame mainFrame) {
        initComponents();
        Course course = new Course();
        Date date = new Date();
        Teacher teacher = new Teacher("john", "John Doe", "Laki-laki", date, "john@gmail.com", "password", "", 50000);
        course.setCategory(new Category("Programming"));
        course.setName("Belajar Pemrogramman");
        course.setTeacher(teacher);
        course.setCreatedAt();
        course.setPrice(50000);
        courses.add(course);
        courses.add(course);
        courses.add(course);
        courses.add(course);
        courses.add(course);
        courses.add(course);
        
        int courseSize = courses.size();

        if (courseSize > 0) {
            double result = (double) courseSize / 2.0;
            int rows = (int) Math.round(result);
            if (rows == 0) {
                rows = 1;
            }
            this.cardPanels.setLayout(new GridLayout(rows, 2, 8, 8));
            for (int i = 0; i < courseSize; i++) {
                CourseCard courseCard = new CourseCard(course);
                this.cardPanels.add(courseCard);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIntroUser = new javax.swing.JLabel();
        cardPanels = new javax.swing.JPanel();
        lblBalance = new javax.swing.JLabel();

        lblIntroUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIntroUser.setText("Halo, User!");

        javax.swing.GroupLayout cardPanelsLayout = new javax.swing.GroupLayout(cardPanels);
        cardPanels.setLayout(cardPanelsLayout);
        cardPanelsLayout.setHorizontalGroup(
            cardPanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );
        cardPanelsLayout.setVerticalGroup(
            cardPanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );

        lblBalance.setText("Saldo: Rp50.000,00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBalance)
                    .addComponent(lblIntroUser)
                    .addComponent(cardPanels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblIntroUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBalance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(cardPanels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardPanels;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblIntroUser;
    // End of variables declaration//GEN-END:variables
}
