/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.oop.academy.presentation.teacher.registration;

import com.oop.academy.InjectionContainer;
import com.oop.academy.application.repositories.teacher.registration.TeacherRegistRepository;
import com.oop.academy.application.service.DatabaseService;
import com.oop.academy.models.Education;
import com.oop.academy.models.Teacher;
import com.oop.academy.models.User;
import com.oop.academy.presentation.MainFrame;
import com.oop.academy.presentation.dashboard.UserDashboardView;
import java.awt.Desktop;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class RegistrationTeacherView extends javax.swing.JPanel {

    private final MainFrame mainFrame;
    private final User currentUser;
    private final DefaultTableModel tableContent;
    private final TeacherRegistRepository teacherRegistRepository
            = InjectionContainer.teacherRegistRepository;
    private final List<Education> educations = new ArrayList();

    public RegistrationTeacherView(MainFrame mainFrame, User currentUser, Teacher teacher) {
        this.mainFrame = mainFrame;
        this.currentUser = currentUser;
        tableContent = new DefaultTableModel(new Object[][]{}, new String[]{
            "No", "Nama Sekolah", "periode", "GPA", "Gelar"
        });

        if (teacher != null) {
            educations.addAll(teacher.getEducations());
        }
        renderTable();
        initComponents();

        if (teacher != null) {
            inputPersonalWeb.setText(teacher.getPersonalWebsiteUrl());
            inputCL.setText(teacher.getCoverLetter());

            inputName.setEnabled(false);
            inputCL.setEnabled(false);
            inputDegree.setEnabled(false);
            inputGpa.setEnabled(false);
            inputPeriod.setEnabled(false);
            inputPersonalWeb.setEnabled(false);
            inputGelar.setEnabled(false);
            btnRegistration.setVisible(false);
            btnUploadCertificate.setEnabled(false);
            btnCancel.setEnabled(false);
            btnDelete.setEnabled(false);
            btnAddEducation.setEnabled(false);
        }
    }

    private void clearInputEducation() {
        this.btnAddEducation.setText("Add");

        this.inputGpa.setText("");
        this.inputPeriod.setText("");
        this.inputName.setText("");
        this.tfCertificate.setText("");
        this.inputGelar.setText("");
    }

    private void renderTable() {
        tableContent.getDataVector().removeAllElements();
        tableContent.fireTableDataChanged();
        tableContent.setRowCount(0);

        int i = 1;
        for (Education educations : educations) {
            this.tableContent.addRow(new Object[]{
                i,
                educations.getName(),
                educations.getAttendPeriod(),
                educations.getGpa(),
                educations.getDegree()});
            i++;
        }
    }

    private void goBack() {
        mainFrame.showView(new UserDashboardView(mainFrame, null));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        inputPeriod = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputGpa = new javax.swing.JTextField();
        btnUploadCertificate = new javax.swing.JButton();
        btnAddEducation = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnRegistration = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        inputPersonalWeb = new javax.swing.JTextField();
        inputDegree = new javax.swing.JLabel();
        inputGelar = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        tfCertificate = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputCL = new javax.swing.JTextArea();
        btnOpenFile = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Form Pendaftaran Guru");

        jLabel3.setText("Nama Sekolah :");

        jLabel4.setText("Lama Periode :");

        jLabel5.setText("Certificate :");

        jLabel6.setText("GPA :");

        btnUploadCertificate.setText("Upload");
        btnUploadCertificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadCertificateActionPerformed(evt);
            }
        });

        btnAddEducation.setText("Add");
        btnAddEducation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEducationActionPerformed(evt);
            }
        });

        table.setModel(this.tableContent);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel8.setText("Surat Lamaran :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("List Education");

        btnRegistration.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegistration.setText("Registration");
        btnRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrationActionPerformed(evt);
            }
        });

        jLabel10.setText("Personal Website :");

        inputDegree.setText("Gelar :");

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnExit.setText("Back");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        tfCertificate.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tfCertificate.setEnabled(false);

        inputCL.setColumns(20);
        inputCL.setRows(5);
        jScrollPane2.setViewportView(inputCL);

        btnOpenFile.setText("Lihat");
        btnOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(inputPersonalWeb))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnExit)
                                .addGap(170, 170, 170)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(inputPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(inputGpa, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnAddEducation, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnUploadCertificate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnOpenFile)
                                        .addGap(18, 18, 18)
                                        .addComponent(inputDegree)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputGelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegistration)
                .addGap(300, 300, 300))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit)
                    .addComponent(jLabel1))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(inputGpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUploadCertificate)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnOpenFile)
                        .addComponent(inputDegree)
                        .addComponent(inputGelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addComponent(btnAddEducation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnCancel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(inputPersonalWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnRegistration)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddEducationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEducationActionPerformed
        String name = inputName.getText();
        String degree = inputGelar.getText();
        File certificate = new File(tfCertificate.getText());
        float Gpa = 0;
        int period = 0;

        try {
            period = Integer.parseInt(inputPeriod.getText());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Out Of "
                    + "Integer");
        }
        try {
            Gpa = Float.parseFloat(inputGpa.getText());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Out Of "
                    + "Float");
        }
        Education newEducation = new Education(name, period, degree,
                Gpa, certificate);
        if ("Add".equals(btnAddEducation.getText())) {
            try {
                educations.add(newEducation);
            } catch (Exception ex) {
                Logger.getLogger(RegistrationTeacherView.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            educations.set(teacherRegistRepository.getSelectedRow(), newEducation);
        }
        clearInputEducation();
        renderTable();

    }//GEN-LAST:event_btnAddEducationActionPerformed

    private void btnUploadCertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadCertificateActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();

        String filename = f.getAbsolutePath();
        tfCertificate.setText(filename);

    }//GEN-LAST:event_btnUploadCertificateActionPerformed

    private void btnRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrationActionPerformed
        User currentUser = DatabaseService.currentUser;
        String coverLetter = inputCL.getText();
        String personalWebsite = inputPersonalWeb.getText();

        Teacher registTeacher = new Teacher(currentUser);
        registTeacher.setEducations(educations);
        registTeacher.setCoverLetter(coverLetter);
        registTeacher.setPersonalWebsiteUrl(personalWebsite);

        try {
            teacherRegistRepository.RegisterTeacher(registTeacher);
            JOptionPane.showMessageDialog(this, "Pendaftaran berhasil!");
            goBack();
        } catch (Exception ex) {
            Logger.getLogger(RegistrationTeacherView.class.getName()).
                    log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegistrationActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        String period;
        String Gpa;
        btnAddEducation.setText("Update");

        int selectedRow = this.table.getSelectedRow();
        if (selectedRow >= 0) {
            teacherRegistRepository.setSelectedRow(selectedRow);
            Gpa = String.valueOf(educations.get(selectedRow).getGpa());
            period = String.valueOf(educations.get(selectedRow).getAttendPeriod());
            this.inputGpa.setText((String) Gpa);
            this.inputPeriod.setText((String) period);
            this.inputName.setText((String) educations.get(selectedRow).getName());
            String path = "";
            if (educations.get(selectedRow).getCertificateUrl() != null) {
                path = educations.get(selectedRow).getCertificateUrl().getAbsolutePath();
            }
            this.tfCertificate.setText(path);
            this.inputGelar.setText((String) educations.get(selectedRow).getDegree());
        }
    }//GEN-LAST:event_tableMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        clearInputEducation();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        goBack();

    }//GEN-LAST:event_btnExitActionPerformed

    private void btnOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFileActionPerformed
        try {
            if (!tfCertificate.getText().isBlank()) {
                Desktop desktop = Desktop.getDesktop();
                desktop.open(new File(tfCertificate.getText()));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnOpenFileActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = this.table.getSelectedRow();
        if (selectedRow != -1) {
            educations.remove(selectedRow);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEducation;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnOpenFile;
    private javax.swing.JButton btnRegistration;
    private javax.swing.JButton btnUploadCertificate;
    private javax.swing.JTextArea inputCL;
    private javax.swing.JLabel inputDegree;
    private javax.swing.JTextField inputGelar;
    private javax.swing.JTextField inputGpa;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputPeriod;
    private javax.swing.JTextField inputPersonalWeb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    private javax.swing.JTextField tfCertificate;
    // End of variables declaration//GEN-END:variables

}
